services:
  - type: web
    name: auditory-diary-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
